<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="TechSpherex.CleanArchitecture.Application.UnitTests" />
    <InternalsVisibleTo Include="TechSpherex.CleanArchitecture.Infrastructure" />
  </ItemGroup>
</Project>
